### PR TITLE
Some temporary patching to get ID urls working OK before redirecting to them

### PR DESCRIPTION
**Pull request by matthew-andrews**
screen shot 2015-05-12 at 13 33 17

### CODE REVIEW

**Comment by matthew-andrews** [comment]
cc @adgad

**Comment by adgad** [comment]
Can we keep that data-concept-id as people:"David Cameron" (not peopleId)

**Comment by matthew-andrews** [comment]
@adgad ooops well spotted!

**Comment by matthew-andrews** [comment]
screen shot 2015-05-12 at 13 49 24

^^ better? @adgad

**Comment by adgad** [comment]
:+1: Maybe double check the pagination buttons, but they'll probably be okay :)

**Pull request merged**
