### PR TITLE
Output streams as an RSS feed

### PR DESCRIPTION
**Pull request by adgad**
@matthew-andrews @commuterjoy @wheresrhys 

screen shot 2015-01-27 at 16 52 00

### CODE REVIEW

**Comment by commuterjoy** [comment]
You'll need to extract something from the Accept header and vary on it.

**Comment by commuterjoy** [comment]
Validate it - http://validator.w3.org/feed/

**Comment by commuterjoy** [comment]
With the &lt;link&gt; elements you probably don't want ever want localhost in there.

**Comment by adgad** [comment]
Added vary header. I wanted to avoid hardcoding 'next.ft.com' so just taking whatever URL used to consume the feed.

**Comment by matthew-andrews** [comment]
then it probably should be FT.com (with its legacy article URL schema :disappointed: )

**Comment by matthew-andrews** [comment]
http://www.ft.com/cms/s/{{uuid}}.html automatically forwards to the right ID

**Pull request merged**
