### PR TITLE
Headline article list

### PR DESCRIPTION
**Pull request by matthew-andrews**
screen shot 2015-05-14 at 09 42 50
screen shot 2015-05-14 at 09 46 08

### CODE REVIEW

**Comment by matthew-andrews** [comment]
Ignore the fact the dates arent relative — this is a bug just affecting me locally

**Comment by adgad** [comment]
Nice.

Search results should be showing the highlighted "matches" though - rather than the subheading.

**Comment by matthew-andrews** [comment]
@adgad i think that's a separate regression http://next.ft.com/search?q=test

**Comment by matthew-andrews** [comment]
hmm  no actually ti is a regression in this PR

**Pull request merged**
