### PR TITLE
Re-scope sub-header navigation styles

### LINKED ISSUE #492: header display issues when components missing
screen shot 2015-06-03 at 11 45 33

cc @i-like-robots

### PR DESCRIPTION
**Pull request by i-like-robots**
Fixes #492 

screen shot 2015-06-03 at 12 07 17

### CODE REVIEW

**Comment by ironsidevsquincy** [comment]
could event use `next-dobi-` as a prefix...

**Comment by ironsidevsquincy** [comment]
could even use `next-dobi-` as a prefix...

**Comment by i-like-robots** [comment]
Everything for now is `.sub-header` ... which could potentially conflict with a more generic sub-header component I guess. But for now we'll live.

**Comment by matthew-andrews** [comment]
^^ @ironsidevsquincy @i-like-robots planning to rename this app to `next-stream` at some point :)

**Pull request merged**
