### PR TITLE
Try to avoid stagnant cache hits on live streams

### PR DESCRIPTION
**Pull request by i-like-robots**
…by appending the current time (rounded down to nearest minute) and testing if returned story ID already exists on the page. Belt and braces.

'Proper' solution would be only fetching stories after given date on the backend I suppose but this _is_ MVP ;-)

### CODE REVIEW

**Comment by i-like-robots** [comment]
CC @matthew-andrews

**Comment by i-like-robots** [comment]
Fix for #534

**Comment by matthew-andrews** [comment]
:+1: 
simples

**Comment by i-like-robots** [comment]
Failure to spell 'stagnant' correctly multiple times. -1.

**Comment by matthew-andrews** [comment]
this didn't pass tests :scream: [i know we have heroku issues right now]

**Comment by i-like-robots** [comment]
I am a bad person. Subconscious merge button mashing despite broken build. Will stop build for the merge.

**Comment by matthew-andrews** [comment]
nah

**Comment by matthew-andrews** [comment]
it's going to fail anyway

**Pull request merged**
