### PR TITLE
Migrate related tags functionality from Slurp to ES

### PR DESCRIPTION
**Pull request by i-like-robots**
So we're not relying on an unsupported API =)

Requires https://github.com/Financial-Times/next-ft-api-client/pull/30

Before:
screen shot 2015-05-26 at 17 12 44

After:
screen shot 2015-05-26 at 17 12 31

### CODE REVIEW

**Comment by matthew-andrews** [comment]
undefined is not a function :)

**Comment by i-like-robots** [comment]
Depends on https://github.com/Financial-Times/next-ft-api-client/pull/30 being merged and bumped

**Comment by i-like-robots** [comment]
@matthew-andrews Should be good to go

**Comment by matthew-andrews** [comment]
:+1:

**Pull request merged**
