### PR TITLE
Curated video

### PR DESCRIPTION
**Pull request by wheresrhys**
@ironsidevsquincy @matthew-andrews

### CODE REVIEW

**Comment by next-team** [comment]
[Image diffs found between branch and production](https://s3-eu-west-1.amazonaws.com/ft-next-qa/image_diffs/dobi/2015-06-17/08:49-1901/failures/index.html)

**Comment by next-team** [comment]
[Image diffs found between branch and production](https://s3-eu-west-1.amazonaws.com/ft-next-qa/image_diffs/dobi/2015-06-17/08:51-1903/failures/index.html)

**Comment by matthew-andrews** [comment]
hmm… @next-team !

**Comment by matthew-andrews** [comment]
:+1:

**Pull request merged**
