### PR TITLE
Do not use related tag IDs because they're unreliable

### PR DESCRIPTION
**Pull request by i-like-robots**
To handle https://github.com/Financial-Times/next-ft-api-client/pull/41

### CODE REVIEW

**Comment by matthew-andrews** [comment]
:+1:

**Comment by next-team** [comment]
[Image diffs found between branch and production](https://s3-eu-west-1.amazonaws.com/ft-next-qa/image_diffs/dobi/2015-06-19/10:46-1956/failures/index.html)

**Comment by i-like-robots** [comment]
Image diff win!

**Comment by matthew-andrews** [comment]
looks like an old version of image diff though :)

**Pull request merged**
